[package]
name = "mock-icrc3-ledger"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["generic_icrc3"]
generic_icrc3 = []

[dependencies]
candid = { workspace = true }
crc32fast = { workspace = true }
ic-cdk = { workspace = true }
icrc-ledger-types = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
