import test from 'node:test';import assert from 'node:assert/strict';import {readFile}from'node:fs/promises';
import {buildGlobalMemo,buildMemo,buildRangeMemo,buildNeuronMemo,buildNeuronRangeMemo,isValidAmount,validatePrincipal} from '../public/memo.js';import {INSTANCES} from '../public/instances.js';import{ICP_API_HOST,queryBackendPricing}from'../public/pricing-client.js';import{pricingMarkup}from'../public/pricing-view.js';
import {renderRuntimeError} from '../public/safe-dom.js';
import {normalizeMode,targetLabels} from '../public/target-view.js';
import {registryMarkup,verifyInstanceConfiguration} from '../public/instance-view.js';
import {createApp} from '../public/app.js';
test('registry contains ICP live and IO planned only',()=>{assert.deepEqual(INSTANCES.map(({id,status,alias})=>({id,status,alias})),[{id:'icp',status:'live',alias:'X'},{id:'io',status:'planned',alias:'I'}]);assert.equal(INSTANCES[0].surplusCanisterId,null);assert.equal(INSTANCES[1].backendCanisterId,null);assert.equal(INSTANCES[1].observedLedgerCanisterId,null);assert.equal(INSTANCES[1].surplusCanisterId,null)});
test('selected alias participates in memo and byte limit',()=>{assert.equal(buildGlobalMemo('X','r5m5y-diaaa-aaaaa-qanaa-cai').memo,'X.r5m5ydiaaaaaaaaqanaacai');assert.equal(buildGlobalMemo('I','uuc56-gyb').memo,'I.uuc56gyb');assert.equal(buildMemo('X',8,'r5m5y-diaaa-aaaaa-qanaa-cai','7','0.01').bytes,32);assert.throws(()=>buildMemo('LONG',8,'r5m5y-diaaa-aaaaa-qanaa-cai','7','0.01'),/32-byte/)});
test('generic decimal validation supports 0, 8 and 18 decimal ledgers',()=>{for(const v of ['1','0.1','0.00000001','10.12345678'])assert.equal(isValidAmount(v,8),true,v);for(const v of ['0','.1','0.000000001','-1','+1','1e2','01'])assert.equal(isValidAmount(v,8),false,v);assert.equal(isValidAmount('1',0),true);assert.equal(isValidAmount('1.0',0),false);assert.equal(isValidAmount('0.000000000000000001',18),true)});
test('single range and global builders preserve generic semantics',()=>{assert.equal(buildMemo('I',8,'uuc56-gyb','7','0.0001').memo,'I.uuc56gyb.7:0.0001');assert.equal(buildRangeMemo('I',8,'uuc56-gyb','7','18','0.0001').memo,'I.uuc56gyb.7-18:0.0001');assert.throws(()=>buildRangeMemo('I',8,'uuc56-gyb','18','7',''),/greater/);assert.throws(()=>buildMemo('I',8,'uuc56-gyb','007',''),/canonical/)});
test('u64 and neuron builders use BigInt without endpoint caps',()=>{assert.equal(buildMemo('I',8,'uuc56-gyb','9007199254740993').memo,'I.uuc56gyb.9007199254740993');assert.equal(buildMemo('I',8,'uuc56-gyb','18446744073709551615').memo,'I.uuc56gyb.18446744073709551615');assert.throws(()=>buildMemo('I',8,'uuc56-gyb','18446744073709551616'),/64-bit/);assert.equal(buildRangeMemo('I',8,'uuc56-gyb','1000','1255').memo,'I.uuc56gyb.1000-1255');assert.throws(()=>buildRangeMemo('I',8,'uuc56-gyb','1000','1256'),/256 targets/);assert.equal(buildNeuronMemo('I',8,'uuc56-gyb','1000000').memo,'I.uuc56gyb.n1000000');assert.equal(buildNeuronRangeMemo('I',8,'uuc56-gyb','1000000','1000255').memo,'I.uuc56gyb.n1000000-1000255');assert.throws(()=>buildNeuronRangeMemo('I',8,'uuc56-gyb','1000000','1000256'),/256 targets/)});
test('neuron labels and availability follow verified capability',()=>{assert.deepEqual(targetLabels('neuron'),{single:'Neuron nonce',start:'Start neuron nonce',end:'End neuron nonce'});assert.deepEqual(targetLabels('range'),{single:'Numbered subaccount',start:'Start subaccount',end:'End subaccount'});assert.equal(normalizeMode('neuron-range',false),'account');assert.equal(normalizeMode('neuron',true),'neuron')});
test('official Principal parsing matches backend subscriber rules',()=>{assert.equal(validatePrincipal('  r5m5y-diaaa-aaaaa-qanaa-cai  '),'r5m5ydiaaaaaaaaqanaacai');assert.equal(validatePrincipal('uuc56-gyb'),'uuc56gyb');for(const value of ['r5m5y-diaaa-aaaaa-qanaa-caj','bad!','a','2vxsx-fae','aaaaa-aa'])assert.throws(()=>validatePrincipal(value));});
test('memo limit applies after validated Principal normalization',()=>{assert.equal(buildMemo('X',8,'r5m5y-diaaa-aaaaa-qanaa-cai','7','0.01').bytes,32);assert.throws(()=>buildMemo('XX',8,'r5m5y-diaaa-aaaaa-qanaa-cai','7','0.01'),/32-byte/)});
test('runtime error rendering uses a text sink',()=>{const classes=[];const node={textContent:'',classList:{add:value=>classes.push(value)}};const hostile='<img src=x onerror=alert(1)>';renderRuntimeError(node,hostile);assert.equal(node.textContent,hostile);assert.deepEqual(classes,['error']);assert.equal('innerHTML' in node,false)});
const raw={initialized:true,current:{account_icp:5n,range_icp:10n,global_icp:50n},current_effective_at:1n,next:[],next_effective_at:2n,next_freeze_at:3n,observed_floor_xdr_permyriad:23147n,floor_observed_at:1n,latest_xdr_permyriad:31250n,latest_observed_at:1n,next_carried_forward_due_to_stale_rate:false};
test('backend principal is mandatory and config plus ICP pricing are queried',async()=>{await assert.rejects(()=>queryBackendPricing(),/registry backend/);let options;const result=await queryBackendPricing({canisterId:'aaaaa-aa',createAgent:async o=>o,createActor:(_f,o)=>(options=o,{get_instance:async()=>({observed_ledger:{toText:()=> 'ledger'},observed_profile:[{symbol:'ICP',decimals:8}]}),get_pricing:async()=>raw})});assert.equal(options.canisterId,'aaaaa-aa');assert.equal(options.agent.host,ICP_API_HOST);assert.equal(result.pricing.current.account_icp,5);assert.match(pricingMarkup({...result.pricing}),/Account subscription: 5 ICP/)});
test('immutable instance verification includes the reviewed surplus recipient',()=>{const principal=text=>({toText:()=>text}),profile={symbol:'ICP',decimals:8,neuron_governance:[]},registry={...INSTANCES[0],observedLedgerCanisterId:'ledger',snsRootCanisterId:null,surplusCanisterId:'treasury'};const instance={observed_ledger:principal('ledger'),sns_root:[],surplus_canister:[principal('treasury')],observed_profile:[profile]};assert.equal(verifyInstanceConfiguration(registry,instance),profile);assert.match(registryMarkup(registry,profile),/Surplus recipient: treasury/);assert.throws(()=>verifyInstanceConfiguration({...registry,surplusCanisterId:'other'},instance),/surplus recipient treasury/);assert.match(registryMarkup({...registry,surplusCanisterId:null}),/Surplus recipient: none/)});
test('frontend has no mutable runtime registry',async()=>{const did=await readFile(new URL('../event_horizon_frontend.did',import.meta.url),'utf8'),rust=await readFile(new URL('../src/lib.rs',import.meta.url),'utf8'),app=await readFile(new URL('../public/app.js',import.meta.url),'utf8');assert.doesNotMatch(did,/http_request_update/);assert.doesNotMatch(rust,/ic_env|set-cookie/i);assert.doesNotMatch(app,/localStorage|document\.cookie|URLSearchParams/)});

const deferred=()=>{let resolve,reject;const promise=new Promise((ok,no)=>{resolve=ok;reject=no});return{promise,resolve,reject}};
const principal=text=>({toText:()=>text});
const liveEntry=(id,backend)=>({id,name:id.toUpperCase(),symbol:'TOK',alias:id.toUpperCase(),status:'live',canonical:true,backendCanisterId:backend,observedLedgerCanisterId:'ledger',snsRootCanisterId:null,surplusCanisterId:null,expectedBackendWasmSha256:'hash'});
const backendResult=(entry,accountIcp)=>({instance:{observed_ledger:principal(entry.observedLedgerCanisterId),sns_root:[],surplus_canister:[],observed_profile:[{symbol:entry.symbol,decimals:8,neuron_governance:[]}]},pricing:{initialized:true,current:{account_icp:accountIcp,range_icp:accountIcp*2,global_icp:accountIcp*10},current_effective_at:1,next:null,next_effective_at:2,next_freeze_at:3,observed_floor_xdr_permyriad:10000,floor_observed_at:1,latest_xdr_permyriad:10000,latest_observed_at:1,next_carried_forward_due_to_stale_rate:false}});

function fakeDocument(){
  const listeners=new Map();
  const makeNode=()=>({textContent:'',innerHTML:'',value:'',disabled:false,hidden:false,classList:{values:new Set(),add(value){this.values.add(value)},remove(value){this.values.delete(value)}},addEventListener(type,handler){listeners.set(type,handler)},append(option){this.options??=[];this.options.push(option);if(!this.value)this.value=option.value}});
  const ids=['instance','instance-info','pricing','scope','single-label','range-start-label','range-end-label','account-fields','single-field','range-fields','memo-output','memo-help','principal','subaccount','range-start','range-end','amount'];
  const nodes=Object.fromEntries(ids.map(id=>[id,makeNode()]));
  nodes.scope.value='account';
  const scopeOptions={neuron:makeNode(),'neuron-range':makeNode()};
  nodes.scope.querySelector=selector=>scopeOptions[selector.match(/value="([^"]+)"/)[1]];
  nodes['amount-label']=makeNode();
  nodes['amount-label'].firstChild={textContent:''};
  nodes['memo-form']=makeNode();
  nodes['memo-form'].elements=[nodes.scope,nodes.principal,nodes.subaccount,nodes['range-start'],nodes['range-end'],nodes.amount];
  return {nodes,getElementById:id=>nodes[id],createElement:()=>makeNode()};
}

function appFixture(instances,queryBackend){const documentRef=fakeDocument();const app=createApp({documentRef,instances,queryBackend,autoLoad:false});return{...app,documentRef}};

test('latest selection wins when an older success arrives last',async()=>{const a=liveEntry('a','backend-a'),b=liveEntry('b','backend-b'),calls={a:deferred(),b:deferred()};const fixture=appFixture([a,b],({canisterId})=>calls[canisterId.endsWith('a')?'a':'b'].promise);const first=fixture.load();fixture.documentRef.nodes.instance.value='b';const second=fixture.load();calls.b.resolve(backendResult(b,22));await second;calls.a.resolve(backendResult(a,11));await first;assert.match(fixture.documentRef.nodes['instance-info'].innerHTML,/Backend: backend-b/);assert.match(fixture.documentRef.nodes.pricing.innerHTML,/Account subscription: 22 ICP/)});
test('stale failure cannot overwrite the latest successful selection',async()=>{const a=liveEntry('a','backend-a'),b=liveEntry('b','backend-b'),calls={a:deferred(),b:deferred()};const fixture=appFixture([a,b],({canisterId})=>calls[canisterId.endsWith('a')?'a':'b'].promise);const first=fixture.load();fixture.documentRef.nodes.instance.value='b';const second=fixture.load();calls.b.resolve(backendResult(b,22));await second;calls.a.reject(new Error('late A failure'));await first;assert.match(fixture.documentRef.nodes.pricing.innerHTML,/Account subscription: 22 ICP/);assert.doesNotMatch(fixture.documentRef.nodes.pricing.textContent,/late A failure/)});
test('planned selection invalidates an outstanding live response',async()=>{const a=liveEntry('a','backend-a'),planned={...liveEntry('planned',null),status:'planned',observedLedgerCanisterId:null,expectedBackendWasmSha256:null};const pending=deferred();const fixture=appFixture([a,planned],()=>pending.promise);const first=fixture.load();fixture.documentRef.nodes.instance.value='planned';await fixture.load();pending.resolve(backendResult(a,11));await first;assert.equal(fixture.documentRef.nodes.pricing.textContent,'Pricing unavailable until launch.');assert.equal(fixture.documentRef.nodes.principal.disabled,true)});
test('backend principal and pricing stay bound to the captured registry entry',async()=>{const a=liveEntry('a','backend-a'),b=liveEntry('b','backend-b'),calls={a:deferred(),b:deferred()};const fixture=appFixture([a,b],({canisterId})=>calls[canisterId.endsWith('a')?'a':'b'].promise);const first=fixture.load();fixture.documentRef.nodes.instance.value='b';const second=fixture.load();calls.b.resolve(backendResult(b,99));await second;calls.a.resolve(backendResult(a,1));await first;assert.match(fixture.documentRef.nodes['instance-info'].innerHTML,/Backend: backend-b/);assert.match(fixture.documentRef.nodes.pricing.innerHTML,/Account subscription: 99 ICP/)});
test('current configuration verification failure leaves builder disabled',async()=>{const a=liveEntry('a','backend-a');const wrong=backendResult(a,11);wrong.instance.observed_ledger=principal('wrong-ledger');const fixture=appFixture([a],async()=>wrong);await fixture.load();assert.match(fixture.documentRef.nodes.pricing.textContent,/Configuration mismatch/);assert.equal(fixture.documentRef.nodes.principal.disabled,true);assert.equal(fixture.documentRef.nodes.instance.disabled,false)});
